# Generated by Django 2.2.3 on 2019-07-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('actionid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('eventsource', models.IntegerField()),
                ('evaltype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('esc_period', models.IntegerField()),
                ('def_shortdata', models.CharField(max_length=255)),
                ('def_longdata', models.TextField()),
                ('recovery_msg', models.IntegerField()),
                ('r_shortdata', models.CharField(max_length=255)),
                ('r_longdata', models.TextField()),
                ('formula', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'actions',
                'managed': False,
            },
        ),
    ]
