# Generated by Django 2.2.3 on 2019-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ongoing_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
