# Generated by Django 2.2.3 on 2019-07-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_ongoing_maintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='type',
            new_name='device_type',
        ),
    ]
